# Generated by Django 2.2 on 2021-04-08 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.TextField()),
                ('summary', models.TextField()),
                ('instructions', models.TextField()),
                ('ready', models.CharField(max_length=10)),
                ('servings', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_added', to='recipe.User')),
                ('users_who_liked', models.ManyToManyField(related_name='recipes_liked', to='recipe.User')),
            ],
        ),
    ]
